FROM php:8.2-fpm

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && apt-get install -y \
        sudo\
        git \
        unzip \
        vim \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        unzip \
        librabbitmq-dev \
        && docker-php-ext-install pdo pdo_mysql zip bcmath \
        && pecl install amqp

RUN docker-php-ext-enable amqp
RUN docker-php-ext-install sockets

RUN curl -sS https://get.symfony.com/cli/installer | bash

WORKDIR /var/www/html/notification-service

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY /notification-service /var/www/html/notification-service

RUN composer install --no-scripts --optimize-autoloader

CMD ["php-fpm"]
