version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      - NGINX_HOST=host.docker.internal
    volumes:
      - ./user-service:/var/www/html/user-service
      - ./notification-service:/var/www/html/notification-service
    depends_on:
      - user-service
      - notification-service
      - rabbitmq
    labels:
      - traefik.enable=true
      - traefik.http.routers.app_router.rule=Host(`${USER_DOMAIN}`,`${NOTIFICATION_DOMAIN}`)
      - traefik.http.routers.app_router.service=web
      - traefik.http.services.web.loadbalancer.server.port=80
    networks:
      - front

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile-php
    volumes:
      - ./user-service:/var/www/html/user-service
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DATABASE_URL=mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}
    depends_on:
      - mysql
    networks:
      - front
      - back

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile-php
    volumes:
      - ./notification-service:/var/www/html/notification-service
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DATABASE_URL=mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}
    depends_on:
      - mysql
    expose:
      - 9000
    networks:
      - front
      - back

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`pma.nextbaskettech.localhost`)
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    networks:
      - front
      - back

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.nextbaskettech.localhost`)
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672

  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - front

networks:
  front:
  back: